//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryContent
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string ApiUrl { get; set; }
        public int CatId { get; set; }
        public Nullable<int> IconId { get; set; }
        public Nullable<int> SchemaContentId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Icon Icon { get; set; }
        public virtual SchemaContent SchemaContent { get; set; }
    }
}
