//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchemaContent
    {
        public SchemaContent()
        {
            this.CategoryContent = new HashSet<CategoryContent>();
        }
    
        public int Id { get; set; }
        public string TitleTag { get; set; }
        public string DescTag { get; set; }
        public string UrlTag { get; set; }
    
        public virtual ICollection<CategoryContent> CategoryContent { get; set; }
    }
}
